
title: Your portfolio
email: youremail@email.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/jekyll-demo" # the subpath of your site, e.g. /blog https://glennevans.github.io
url: "" # the base hostname & protocol for your site, e.g. http://example.com #/jekyll-demo

markdown: kramdown

permalink: /:categories/:title/
#permalink:  pretty

sass:
  style: compact # possible values: nested expanded compact compressed
  